### ISSUE TITLE
Error loading protobuf files

### ISSUE THREAD

**Issue by ChandlerBuck** [tobinbradley/pg-vector-tile-server#1]
What client are you using to render the protobuf files in your example? I am using leaflet version 1.0.0 and I am getting an error; Uncaught Error: Unimplemented type: 4 when I try to load the files.

**Comment by tobinbradley** [comment]
Leaflet by itself won't show protobuf files, though there are [plugins available](http://leafletjs.com/plugins.html#vector-tiles) for basic rendering.

For complex rendering, particularly in regards to labeling, [Mapbox GL JS](https://www.mapbox.com/mapbox-gl-js/api/) is best in class at the moment.
